import cursorIcons from '../image/stage_cursor';

export const CURSOR_STYLE = {
    DRAW_STROKE: `url("${cursorIcons.drawStroke}") 0 0, crosshair`,
    DRAW_RECT: `url("${cursorIcons.drawRect}") 0 0, crosshair`,
    ERASE_STROKE: `url("${cursorIcons.eraseStroke}") 0 0, crosshair`,
    ERASE_RECT: `url("${cursorIcons.eraseRect}") 0 0, crosshair`,
    ADD_STROKE: `url("${cursorIcons.addStroke}") 0 16, crosshair`,
    ADD_RECT: `url("${cursorIcons.addRect}") 0 0, crosshair`,
    REMOVE_STROKE: `url("${cursorIcons.removeStroke}") 0 16, crosshair`,
    REMOVE_RECT: `url("${cursorIcons.removeRect}") 0 0, crosshair`,
    GLOBAL_ERASE_STROKE: `url("${cursorIcons.globalEraseStroke}") 0 0, crosshair`,
    GLOBAL_ERASE_RECT: `url("${cursorIcons.globalEraseRect}") 0 0, crosshair`,
    CUT_STROKE: `url("${cursorIcons.cutStroke}") 0 16, crosshair`,
    CUT_RECT: `url("${cursorIcons.cutRect}") 0 0, crosshair`,
    TOP: `url("${cursorIcons.top}") 8 8, crosshair`,
    UP: `url("${cursorIcons.up}") 8 8, crosshair`,
    DOWN: `url("${cursorIcons.down}") 8 8, crosshair`,
    LEFT: `url("${cursorIcons.left}") 8 8, crosshair`,
    RIGHT: `url("${cursorIcons.right}") 8 8, crosshair`,
    PATH: `url("${cursorIcons.path}") 8 8, crosshair`,
    CHANGE: `url("${cursorIcons.change}") 8 8, crosshair`,
    LOCKED: `url("${cursorIcons.locked}") 8 8, not-allowed`,
    WAIT: 'wait',
    NOT_ALLOWED: 'not-allowed',
};
